/**
 * Auto-generated TypeScript types for Directus collections
 * Generated from: https://paraiges-directus.neodelta.dev
 * Generated at: 2025-10-28T13:09:05.365Z
 * 
 * Generated by fetching sample data from each collection
 * Run 'npm run directus:types' to regenerate
 */

/**
 * beers collection
 */
export interface Beers {
  id?: number;
  title?: string;
  description?: string;
  featured_image?: string;
  brewery?: number;
  ibu?: number;
  style?: number;
  available_at?: number[];
}

/**
 * breweries collection
 */
export interface Breweries {
  id?: number;
  title?: string;
  country?: string;
}

/**
 * establishments collection
 */
export interface Establishments {
  id?: number;
  title?: string;
  line_address_1?: string;
  line_address_2?: any;
  zipcode?: string;
  city?: string;
  country?: string;
  short_description?: string;
  description?: string;
  featured_image?: string;
  anniversary?: string;
  logo?: string;
}

/**
 * news collection
 */
export interface News {
  id?: number;
  title?: string;
  content?: string;
  featured_image?: string;
  concerned_establishments?: number[];
}

/**
 * quests collection
 */
export interface Quests {
}

/**
 * styles collection
 */
export interface Styles {
  id?: number;
  title?: string;
  description?: any;
}

/**
 * beers_establishments collection
 */
export interface BeersEstablishments {
  id?: number;
  beers_id?: any;
  establishments_id?: number;
}

/**
 * news_establishments collection
 */
export interface NewsEstablishments {
  id?: number;
  news_id?: number;
  establishments_id?: number;
}

/**
 * level_thresholds collection
 */
export interface LevelThresholds {
  id?: number;
  level?: number;
  xp_required?: number;
  name?: string;
  description?: string;
  sort_order?: number;
}

/**
 * Directus Schema - Mapping of collection names to their types
 */
export interface DirectusSchema {
  beers: Beers[];
  breweries: Breweries[];
  establishments: Establishments[];
  news: News[];
  quests: Quests[];
  styles: Styles[];
  beers_establishments: BeersEstablishments[];
  news_establishments: NewsEstablishments[];
  level_thresholds: LevelThresholds[];
}
